program: optimize_fishnchips.py
method: bayes
metric:
  goal: minimize
  name: loss
parameters:
  signal_window_size: 
    values: [300, 420, 510]
  attention_blocks: 
    values: [1,2,3,4,5]
  cnn_blocks: 
    values: [5,6,7]
  dff: 
    value: 512  
  num_heads: 
    values: [2, 4, 8]
  dropout_rate: {
    distribution: uniform,
    min: 0.15,
    max: 0.25
  }
  maxpool_kernel: 
    values: [4,6]
  epochs:
    value: 1