program: optimize_fishnchips.py
method: random
metric:
  goal: minimize
  name: loss
parameters:
  signal_window_size: 
    values: [300,600,900,1200]
  attention_blocks: 
    values: [4,6,8,10]
  cnn_blocks: 
    values: [2, 5, 7]
  dff: 
    values: [256, 512, 1024]
  num_heads: 
    values: [5, 10, 25]
  dropout_rate: 
    values: [0.1, 0.15, 0.2]
  maxpool_kernel: 
    values: [2, 4, 6]
  epochs:
    value: 1